export const UPDATE_COLOR_THEME = 'UPDATE_COLOR_THEME';

export const FETCH_USER_AUTH = 'FETCH_USER_AUTH';
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';

export const SAVE_PROFILE_START = 'SAVE_PROFILE_START';
export const SAVE_PROFILE_DONE = 'SAVE_PROFILE_DONE';

export const MOVE_TO_PROFILE = 'MOVE_TO_PROFILE';
export const MOVE_TO_TRAIN_AI = 'MOVE_TO_TRAIN_AI';
export const MOVE_TO_MATCHES = 'MOVE_TO_MATCHES';
